name: gym_app
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.2.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cloud_firestore: ^0.12.9
  firebase_core: ^0.4.0
  firebase_auth: ^0.14.0
  google_sign_in: ^4.0.7
  provider: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  # flutter_launcher_icons: "^0.7.3"

# flutter_icons:
#   android: "launcher_icon"
#   ios: true
#   image_path: "assets/icon/icon.png"

flutter:
  uses-material-design: true
